import React, { useCallback, useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { AppHeader, BottomNav, Page, PrimaryButton, StateMessage } from '../components/UI';
import { useAuth } from '../context/AuthContext';
import { api } from '../services/api';
import { scheduleDevelopmentTestNotification, syncLocalNotifications } from '../services/notificationService';
import { colors, styles as theme } from '../theme';
import { ReminderSettings } from '../types';

export function ReminderSettingsScreen({ onNavigate }: { onNavigate: (tab: string) => void }) {
  const { token, user } = useAuth();
  const [settings, setSettings] = useState<ReminderSettings | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const load = useCallback(async () => { if (!token) return; try { setSettings(await api.getReminderSettings(token)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load reminder settings.'); } finally { setLoading(false); } }, [token]);
  useEffect(() => { load(); }, [load]);
  async function save() { if (!token || !settings || !user) return; setSaving(true); setError(''); setMessage(''); try { const saved = await api.updateReminderSettings(token, settings); setSettings(saved); const reminders = await api.getReminders(token); const permission = await syncLocalNotifications(reminders.reminders, user.name); setMessage(permission === 'denied' ? 'Notifications are turned off. You can enable them in device settings.' : permission === 'unavailable' ? 'Browser notifications are unavailable here; settings are saved for native Expo.' : 'Reminder settings saved and schedule updated.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to save reminder settings.'); } finally { setSaving(false); } }
  async function testNotification() { setError(''); const result = await scheduleDevelopmentTestNotification(); setMessage(result === 'granted' ? 'Development test reminder scheduled for about 10 seconds from now.' : result === 'denied' ? 'Notifications are turned off. You can enable them in device settings.' : 'Test notifications are unavailable on Expo Web.'); }
  if (loading) return <View style={theme.page}><AppHeader subtitle="Reminder settings" /><Page><StateMessage title="Loading reminder settings..." /></Page></View>;
  if (error && !settings) return <View style={theme.page}><AppHeader subtitle="Reminder settings" /><Page><StateMessage title="Settings unavailable" detail={error} action="Try again" onAction={load} /></Page></View>;
  if (!settings) return null;
  const update = (patch: Partial<ReminderSettings>) => setSettings({ ...settings, ...patch });
  return <View style={theme.page}><AppHeader subtitle="Reminder settings" /><Page><Text style={theme.title}>Stay gently in the loop</Text><Text style={[theme.subtitle, settingsStyle.intro]}>Choose which estimated cycle reminders belong to your account.</Text><View style={theme.card}><SettingRow label="Period check-in" detail="Ask whether your period started" value={settings.period_checkin_enabled} onChange={() => update({ period_checkin_enabled: !settings.period_checkin_enabled })} /><SettingRow label="Upcoming period reminder" detail="A calm reminder before your estimate" value={settings.upcoming_enabled} onChange={() => update({ upcoming_enabled: !settings.upcoming_enabled })} /><Text style={settingsStyle.label}>UPCOMING REMINDER TIMING</Text><View style={settingsStyle.timingRow}>{[['3_days', '3 days before'], ['1_day', '1 day before'], ['both', 'Both']].map(([value, label]) => <Pressable key={value} onPress={() => update({ upcoming_timing: value as ReminderSettings['upcoming_timing'] })} style={[settingsStyle.timing, settings.upcoming_timing === value && settingsStyle.timingActive]}><Text style={[settingsStyle.timingText, settings.upcoming_timing === value && settingsStyle.timingActiveText]}>{label}</Text></Pressable>)}</View><Text style={settingsStyle.note}>Predictions are estimates. Reminders use your local timezone: {settings.timezone}.</Text>{message && <Text style={settingsStyle.success}>{message}</Text>}{error && <Text style={settingsStyle.error}>{error}</Text>}<PrimaryButton label="Save reminder settings" onPress={save} loading={saving} />{__DEV__ && <Pressable onPress={testNotification} style={settingsStyle.devButton}><Text style={settingsStyle.devText}>CycleCare Test Reminder (development)</Text></Pressable>}</View></Page><BottomNav active="profile" onChange={onNavigate} /></View>;
}

function SettingRow({ label, detail, value, onChange }: { label: string; detail: string; value: boolean; onChange: () => void }) { return <View style={settingsStyle.row}><View style={{ flex: 1 }}><Text style={settingsStyle.rowLabel}>{label}</Text><Text style={settingsStyle.rowDetail}>{detail}</Text></View><Pressable accessibilityRole="switch" accessibilityState={{ checked: value }} onPress={onChange} style={[settingsStyle.switch, value && settingsStyle.switchOn]}><View style={[settingsStyle.knob, value && settingsStyle.knobOn]} /></Pressable></View>; }
const settingsStyle = StyleSheet.create({ intro: { marginTop: 7, marginBottom: 20 }, row: { flexDirection: 'row', alignItems: 'center', gap: 15, paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: colors.line }, rowLabel: { color: colors.ink, fontSize: 16, fontWeight: '700' }, rowDetail: { color: colors.muted, fontSize: 12, marginTop: 4 }, switch: { width: 50, height: 29, borderRadius: 16, backgroundColor: colors.line, padding: 3, justifyContent: 'center' }, switchOn: { backgroundColor: colors.burgundy }, knob: { width: 23, height: 23, borderRadius: 12, backgroundColor: colors.paper }, knobOn: { alignSelf: 'flex-end' }, label: { color: colors.burgundy, fontSize: 11, fontWeight: '800', letterSpacing: 1.1, marginTop: 22, marginBottom: 10 }, timingRow: { gap: 8 }, timing: { borderRadius: 14, backgroundColor: colors.mist, padding: 13 }, timingActive: { backgroundColor: colors.plum }, timingText: { color: colors.ink, fontWeight: '700', fontSize: 13 }, timingActiveText: { color: colors.paper }, note: { color: colors.muted, fontSize: 12, lineHeight: 18, marginVertical: 20 }, success: { color: '#245B36', backgroundColor: colors.success, padding: 11, borderRadius: 12, marginBottom: 12 }, error: { color: colors.burgundy, backgroundColor: colors.warning, padding: 11, borderRadius: 12, marginBottom: 12 }, devButton: { borderWidth: 1, borderStyle: 'dashed', borderColor: colors.muted, borderRadius: 14, padding: 12, marginTop: 12, alignItems: 'center' }, devText: { color: colors.muted, fontSize: 12, fontWeight: '700' } });